# Generated by Django 3.1.1 on 2020-09-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0009_auto_20200928_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='INS_COMPANY_NAME',
        ),
        migrations.RemoveField(
            model_name='car',
            name='INS_FROM_DATE',
        ),
        migrations.RemoveField(
            model_name='car',
            name='INS_TOTAL_AMT',
        ),
        migrations.RemoveField(
            model_name='car',
            name='INS_TO_DATE',
        ),
        migrations.RemoveField(
            model_name='car',
            name='INS_TYPE',
        ),
        migrations.RemoveField(
            model_name='car',
            name='OTH_DELIVERY_DATE',
        ),
        migrations.RemoveField(
            model_name='car',
            name='OTH_EXPENSE_NAME',
        ),
        migrations.RemoveField(
            model_name='car',
            name='OTH_EXPENSE_PRICE',
        ),
        migrations.RemoveField(
            model_name='car',
            name='OTH_TRANS_CHARGE',
        ),
        migrations.RemoveField(
            model_name='car',
            name='RTO_BATTERY_NO',
        ),
        migrations.RemoveField(
            model_name='car',
            name='RTO_CHESSISE_NO',
        ),
        migrations.RemoveField(
            model_name='car',
            name='RTO_ENG_NO',
        ),
        migrations.RemoveField(
            model_name='car',
            name='RTO_KEY_NO',
        ),
        migrations.RemoveField(
            model_name='car',
            name='RTO_NUM_PLT_CHARGE',
        ),
        migrations.RemoveField(
            model_name='car',
            name='RTO_NUM_PLT_NO',
        ),
        migrations.RemoveField(
            model_name='car',
            name='RTO_REG_CHARGE',
        ),
        migrations.RemoveField(
            model_name='car',
            name='date_modified',
        ),
        migrations.CreateModel(
            name='RTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RTO_REG_CHARGE', models.IntegerField()),
                ('RTO_NUM_PLT_CHARGE', models.IntegerField()),
                ('RTO_NUM_PLT_NO', models.CharField(max_length=20, unique=True)),
                ('RTO_ENG_NO', models.CharField(max_length=20, unique=True)),
                ('RTO_CHESSISE_NO', models.CharField(max_length=20, unique=True)),
                ('RTO_KEY_NO', models.CharField(max_length=20, unique=True)),
                ('RTO_BATTERY_NO', models.CharField(max_length=20, unique=True)),
                ('CUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAR.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OTHER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTH_TRANS_CHARGE', models.IntegerField()),
                ('OTH_DELIVERY_DATE', models.DateField()),
                ('OTH_EXPENSE_NAME', models.CharField(max_length=20)),
                ('OTH_EXPENSE_PRICE', models.IntegerField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('CUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAR.customer')),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INS_COMPANY_NAME', models.CharField(max_length=20)),
                ('INS_TYPE', models.CharField(max_length=20)),
                ('INS_TOTAL_AMT', models.IntegerField()),
                ('INS_TO_DATE', models.DateField()),
                ('INS_FROM_DATE', models.DateField()),
                ('CUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAR.customer')),
            ],
        ),
    ]
