# Generated by Django 3.1.1 on 2020-10-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0014_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAR_MODEL', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
