# Generated by Django 3.1.1 on 2020-10-05 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0015_aadcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsType',
            fields=[
                ('ID_ins', models.AutoField(primary_key=True, serialize=False)),
                ('Ins_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='AadCar',
        ),
        migrations.AlterField(
            model_name='car',
            name='CAR_MODEL',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CUS_MO',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter 10 digits ', regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CUS_Zip',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='\\d[0-9]')]),
        ),
        migrations.AlterField(
            model_name='rto',
            name='RTO_CHESSISE_NO',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Z0-9]{16,17}$')]),
        ),
        migrations.AlterField(
            model_name='rto',
            name='RTO_ENG_NO',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Z0-9]{16,17}$')]),
        ),
        migrations.AlterField(
            model_name='rto',
            name='RTO_KEY_NO',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Z0-9]{16,17}$')]),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='INS_TYPE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CAR.instype'),
        ),
    ]
