# Generated by Django 3.1.1 on 2020-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0016_auto_20201005_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CUS_DIST',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='customer',
            name='CUS_TALUKA',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='INS_TYPE',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='InsType',
        ),
    ]
