# Generated by Django 3.1.1 on 2020-10-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0017_auto_20201005_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CUS_DIST',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CUS_TALUKA',
        ),
    ]
