# Generated by Django 3.1.1 on 2020-10-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0018_auto_20201005_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CUS_TALUKA',
            field=models.CharField(default='Null', max_length=69),
        ),
    ]
