# Generated by Django 3.1.1 on 2020-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0019_customer_cus_taluka'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CUS_DIST',
            field=models.CharField(default='Null', max_length=69),
        ),
    ]
