# Generated by Django 3.1.1 on 2020-10-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0020_customer_cus_dist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CUS_DIST',
        ),
    ]
