# Generated by Django 3.1.1 on 2020-10-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAR', '0021_remove_customer_cus_dist'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rto',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
